//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeowMeowBeenz.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GebruikerPunten
    {
        public int Id { get; set; }
        public int GeverId { get; set; }
        public int OntvangerId { get; set; }
        public Nullable<int> Punten { get; set; }
    
        public virtual Gebruiker Gebruiker { get; set; }
        public virtual Gebruiker Gebruiker1 { get; set; }
    }
}
