//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeowMeowBeenz.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groep()
        {
            this.GebruikerGroep = new HashSet<GebruikerGroep>();
        }
    
        public int Id { get; set; }
        public string Groepsnaam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GebruikerGroep> GebruikerGroep { get; set; }
    }
}
